"""
AI Monitor 설정
"""
from datetime import timezone, timedelta

# 타임존: KST (UTC+9)
KST = timezone(timedelta(hours=9))

# 모니터링 대상 GitHub 사용자 → Slack 표시명
TEAM_MEMBERS = {
    # Phase 1 (우선순위)
    "hslee-byte": "HS",
    "annnzel": "Ann",
    "teo-hash": "TEO",
    "ghks18g": "Freddie",
    "uno-515": "Hook",
    "jesseorbit": "Jesse",
    # Phase 2 (추가 구성원)
    "RaeOfJune": "Rae",
    "Dev-Arkpoint": "Mew",
    # GitHub org 미가입 — 가입 후 login 업데이트 필요
    # "???": "두영",
    # "???": "Harry",
}

# OS username → 표시명 (session_collector가 OS username으로 저장)
OS_USERNAME_MAP = {
    "hs": "HS",
    "kyongeunlee": "Ann",
    "freddie": "Freddie",
    "ann": "Ann",
    "teo": "TEO",
    "Teo": "TEO",
    "hook": "Hook",
    "jesse": "Jesse",
    "jessesung": "Jesse",
    "rae": "Rae",
    "mew": "Mew",
    "dooyoung": "두영",
    "harry": "Harry",
    "uno": "Uno",
}

# GitHub org
GITHUB_ORG = "Ark-Point"

# Slack 채널
SLACK_CHANNEL_ID_ENV = "SLACK_AI_LAB_CHANNEL"

# AI 커밋 감지 패턴
AI_COMMIT_MARKERS = [
    "Co-Authored-By: Claude",
    "Co-authored-by: Claude",
    "🤖 Generated with",
    "Generated with Claude",
    "Co-Authored-By: Cursor",
    "co-authored-by: cursor",
    "generated by ai",
    "ai-generated",
]

# AI 관련 Slack 키워드
AI_KEYWORDS = [
    "claude", "gpt", "chatgpt", "ai", "에이전트", "agent",
    "프롬프트", "prompt", "llm", "copilot", "cursor",
    "자동화", "automation", "워크플로우", "workflow",
    "vibe coding", "바이브코딩",
]
